<?php
/**
 * Copyright © Klarna Bank AB (publ)
 *
 * For the full copyright and license information, please view the NOTICE
 * and LICENSE files that were distributed with this source code.
 */

/** @var Klarna\Siwk\Block\Login $block */
/** @var Magento\Framework\Escaper $escaper */

if ($block->isSiwkEnabled() && $block->isSiwkOnPositionEnabled($block->getPosition())): ?>
    <script>
        window.addEventListener('klarna-sdk-ready', function (event) {
            const PluginKlarnaWebSdk = event.detail.sdk;

            const siwkButton = PluginKlarnaWebSdk.Identity.button({
                id: "klarna-identity-button",
                scope: "<?= $escaper->escapeUrl($block->getScopes()) ?>",
                interactionMode: '<?= $escaper->escapeUrl($block->getInteractionMode()) ?>',
                redirectUri: '<?= $escaper->escapeUrl($block->getRedirectUrl()) ?>',
                hideOverlay: false,
                shape: "<?= $escaper->escapeUrl($block->getButtonShape()) ?>",
                theme: "<?= $escaper->escapeUrl($block->getButtonTheme()) ?>",
                logoAlignment: "<?= $escaper->escapeUrl($block->getButtonAlignment()) ?>",
                locale: "<?= $escaper->escapeUrl($block->getLocale()) ?>"
            })
            siwkButton.mount("#klarna_siwk_container");

            PluginKlarnaWebSdk.Identity.on("signin", (data) => {
                require([
                    'mage/storage',
                    'Magento_Customer/js/customer-data',
                    'mage/translate'
                ], function (storage, customerData, $t) {
                    async function execute() {

                        storage.post(
                            '<?= $escaper->escapeUrl($block->getAjaxUpdateUrl()) ?>',
                            JSON.stringify(
                                {
                                    'refresh_token': data['user_account_linking']['user_account_linking_refresh_token'],
                                    'id_token': data['user_account_linking']['user_account_linking_id_token'],
                                    'klarna_customer_id': data['user_account_profile']['sub']
                                }
                            ),
                            false,
                            'application/json'
                        ).always(function (data, textStatus) {
                            if (textStatus === 'error') {
                                customerData.set('messages', {
                                    messages: [{
                                        type: 'error',
                                        text: $t('Signing in with Klarna failed.')
                                    }]
                                });
                            } else {
                                var sections = ['cart'];
                                customerData.invalidate(sections);
                                customerData.reload(sections, true);

                                window.location.href = BASE_URL;
                            }
                        });
                    }
                    execute();
                });
            });
        });
    </script>
    <div id="klarna_siwk_container"></div>
    <br />
<?php endif ?>